### ISSUE TITLE
Missing parameter cfg.loss.zoom in trainval_sgaligner.py

### ISSUE THREAD

**Issue by Andy20178** [sayands/sgaligner#1]
Hello,

I encountered an issue while running the trainval_sgaligner.py script with the following command:
python trainers/trainval_sgaligner.py --config ../configs/scan3r/scan3r_ground_truth.yaml
At line 28 of the trainval_sgaligner.py file, the code raises an error: AttributeError: loss. It seems that the self.zoom attribute is not properly set due to the absence of the cfg.loss.zoom parameter.

**Comment by sayands** [comment]
Hi, thanks for pointing it out. I have updated the config files now.
