### ISSUE TITLE
How is the graph structure constructed?

### ISSUE THREAD

**Issue by glennliu** [sayands/sgaligner#6]
Hi @sayands , thanks for your interesting work. 
I have question regrading to the structure embedding. In the paper, it says

> We represent this information in the form of a structure graph: node features are the relative translation between object instances, and edges are the aforementioned relationships. We calculate relative translation by taking the distance between the object instance consisting of the highest number of relationships and that of any other object instance in the scene.

And I find the related parts of the code in ```dataset/scan3r.py```. The node is relative translation [here](https://github.com/sayands/sgaligner/blob/c4ad97d0aeaabb2ea2e415bb834c1618601d252d/src/datasets/scan3r.py#L118), while the edges are  [here](https://github.com/sayands/sgaligner/blob/c4ad97d0aeaabb2ea2e415bb834c1618601d252d/src/datasets/scan3r.py#L100).

I'm just confused how the graph structure is built:
1. For the nodes, since each node can have multiple edges, how to choose one relative translation as a node feature? In Fig2 (b), each node in the visualization is marked with $O_{ij}$. The visualization makes me think each node only contains self-attributes. How do you construct the graph node embeddings? Have you consider using the self-attributes such as semantic info to represent the node?
3. For the edges, you concatenate ```src_edges``` and ```tar_edges```. Does that mean the edges contain both intra-graph and inter-graph relationships? Then how do you construct the edges? For example, if consider inter-graph edges between $G_1$ and $G_2$, do you consider all the possible edges between the two graph? (then you have $|G_1| \cdot |G_2|$ edges).

Thanks for your time.
Glen

**Comment by sayands** [comment]
Hello!

1. Each node is an object in the scene represented as $O_{ij}$. The relative translation we use is the translation of the object from the root object where the root is the object with the most number of edges. We calculate it using the object instance point clouds as implemented [here](https://github.com/sayands/sgaligner/blob/main/preprocessing/scan3r/preprocess.py#L92). Our structure encoder takes in a graph where the nodes are the objects and edges are the relationships between the objects, eg, left, right, etc. We capture the semantic information using the object encoder which takes in point clouds per instance and outputs an embedding.

2. This is just an implementation method to pass everything together in the dataloader, and then process it in SGAligner [here](https://github.com/sayands/sgaligner/blob/main/src/aligner/sg_aligner.py#L84). The edges are only intra-graph relationships, as defined in the 3RScan dataset.

Hope this helps!
