### ISSUE TITLE
Preprocess run failure

### ISSUE THREAD

**Issue by glennliu** [sayands/sgaligner#8]
Hi, 

I'm running ```preprocessing/scan3r/preprocess.py```. It says a file is missing,

```
Exception has occurred: FileNotFoundError
[Errno 2] No such file or directory: '/data2/sgalign_data/out/files/relationships_subscenes_val.json'
  File "/home/cliuci/code_ws/sgaligner/utils/common.py", line 24, in load_json
    file = open(filename)
  File "/home/cliuci/code_ws/sgaligner/preprocessing/scan3r/preprocess.py", line 230, in process_data
    rel_json = common.load_json(osp.join(data_dir, 'files', rel_json_filename))['scans']
  File "/home/cliuci/code_ws/sgaligner/preprocessing/scan3r/preprocess.py", line 365, in <module>
    data_dir, data_write_dir, mode = process_data(args, cfg, rel2idx)
FileNotFoundError: [Errno 2] No such file or directory: '/data2/sgalign_data/out/files/relationships_subscenes_val.json'
```

**Comment by sayands** [comment]
This happens because you might not have run dataset generation which generates the subscans using 3RScan and dumps the scene graphs as triplets. Please have a look at dataset generation section in the readme.

**Comment by glennliu** [comment]
I tried to generate the data again. For some reasons, the generated ```out/files/objects_subscenes_val.json``` does not have any valid scans. I use the original parameters. 
Is there any selection on generate scans in the file?

**Comment by sayands** [comment]
Can you show an example of how does an entry in the file look like? Is it only in `objects_subscenes_val.json` or the others as well?

**Comment by glennliu** [comment]
Hi 

I followed the instruction and run ```bash scripts/generate_subscans_scan3r_gt.sh```. 
I cleaned up the entire dataset space and run the script again. It is now solved. I can process the generated data now. 

In evaluation, I meet another dependency issue. 
I run ```/src/trainers/trainval_eva.py```. It says I didn't install ```pointnet2_utils```.  The ```pct.py``` used pointnet backbone I believe. 
So, which version of pointnet2_util do you use? I didn't see pointnet in the install instruction.

Thanks

**Comment by sayands** [comment]
Glad to know it works and thanks for the catch, I have updated the readme. Please follow [PointCloudTransformer](https://github.com/qinglew/PointCloudTransformer) repository for installing `pointnet2_ops_lib`.
